# Bases de WQSym

In [1]:
from wqsym import *
from packed_words import *
WQSym = WordQuasiSymmetricFunctions(QQ);
WQSym.inject_shorthands(); # Cette ligne permet de pouvoir utiliser toutes les bases de WQSym implémentées
M.options.objects = 'words';
M.options.display = 'compact'

Defining M as shorthand for Word Quasi-symmetric functions over Rational Field in the Monomial basis
Defining X as shorthand for Word Quasi-symmetric functions over Rational Field in the Characteristic basis
Defining C as shorthand for Word Quasi-symmetric functions over Rational Field in the Cone basis
Defining Q as shorthand for Word Quasi-symmetric functions over Rational Field in the Q basis
Defining Phi as shorthand for Word Quasi-symmetric functions over Rational Field in the Phi basis
Defining O as shorthand for Word Quasi-symmetric functions over Rational Field in the O basis
Defining P as shorthand for Word Quasi-symmetric functions over Rational Field in the P basis
Defining R as shorthand for Word Quasi-symmetric functions over Rational Field in the RightWeakOrder basis
Defining GL as shorthand for Word Quasi-symmetric functions over Rational Field in the GL basis
Defining SR as shorthand for Word Quasi-symmetric functions over Rational Field in the SR basis


Nous ne parlerons pas ici des bases $\mathbb{X}$, $\mathbb{C}$ et $\Phi$  qui sont déjà dans Sage et dont je ne me sers pas.

La base $\mathbb{M}$ est la base monomiale définie par 
$$\mathbb{M}_u := \sum_{\substack{w \in \mathcal{A}^*,\\pack(w) = u}}w.$$

Les bases $\mathbb{Q}$, $\mathbb{R}$, $\mathbb{O}$ et $\mathbb{P}$ sont les bases définies dans l'article $\textit{Decompositions of packed words and self duality of Word Quasisymmetric Functions}$.

### TITRE

Produits, demis-produits, coproduits et demis-coproduits sont implémentés pour les bases $\mathbb{M}$, $\mathbb{Q}$ et $\mathbb{R}$. 

Voici des exemples pour chacune des opérations dans la base $\mathbb{M}$.

In [2]:
M[1,2,1] * M[2,1]

M[12143] + M[12132] + M[13142] + M[13132] + M[14132] + M[12131] + M[12121] + M[13121] + M[23241] + M[23231] + M[24231] + M[23221] + M[34321]

In [3]:
M[1,2,1] << M[2,1]

M[14132] + M[13121] + M[24231] + M[23221] + M[34321]

In [4]:
M[1,2,1] >> M[2,1]

M[12143] + M[12132] + M[13142] + M[13132] + M[12131] + M[12121] + M[23241] + M[23231]

Attention, il faut toujours mettre les parenthèses avec les demis-produits, les priorités avec l'addition ne sont pas gérées!

In [5]:
M[1,2,1] * M[2,1] == (M[1,2,1] << M[2,1]) + (M[1,2,1] >> M[2,1])

True

In [6]:
M[2,4,3,1,1,2,4,2].coproduct()

M[] # M[24311242] + M[11] # M[132131] + M[21122] # M[212] + M[231122] # M[11] + M[24311242] # M[]

In [7]:
M.left_coproduct(M[2,4,3,1,1,2,4,2])

M[21122] # M[212] + M[231122] # M[11]

In [8]:
M.right_coproduct(M[2,4,3,1,1,2,4,2])

M[11] # M[132131]

In [9]:
p = PackedWord([2,4,3,1,1,2,4,2]);
M.coproduct(M[p]) - (M.left_coproduct(M[p]) + M.right_coproduct(M[p]))

M[] # M[24311242] + M[24311242] # M[]

De même pour les bases $\mathbb{Q}$ et $\mathbb{R}$ (produits, demis-produits, coproduits et demis-coproduits) en voici deux exemples.

In [10]:
Q[1,2,1] << Q[2,1]

Q[34321] + Q[24231] + Q[14132]

In [11]:
R[1,2,1] >> R[2,1]

R[12143] + R[12413] + R[14213] + R[41213]

On parlera plus tard des produits et coproduits dans les bases $\mathbb{O}$ et $\mathbb{P}$

Les changements de bases fonctionnent bien, mais parfois pour calculer l'inverse je n'ai pas implémenté mieux que de calculer la matrice complète puis de l'inverser. Voici donc les sens qui fonctionnent bien:
- $\mathbb{M}$ $\leftrightarrow$ $\mathbb{Q}$
- $\mathbb{O}$ $\rightarrow$ $\mathbb{Q}$
- $\mathbb{P}$ $\rightarrow$ $\mathbb{R}$

Finalement, quand j'ai un élément dans la base $\mathbb{O}$ ou $\mathbb{P}$, j'utilise les définitions basés sur les arbres. Dans l'autre sens je fais juste l'inverse de la matrice complète. Il est surement possible d'améliorer cette partie.

Enfin l'isomorphisme entre $\mathbb{O}$ et $\mathbb{P}$ est codé comme un simple changement de base.

- $\mathbb{O}$ $\leftrightarrow$ $\mathbb{P}$

Pour chacun des changement de bases nous pourrons observer la matrice de changement de base en taille 3.

In [12]:
matr_chgmt_base_osp = lambda X,Y, n: matrix([[Y(X(mu)).coefficient(sigma) for mu in OrderedSetPartitions(n)] for sigma in OrderedSetPartitions(n)])

#### Changement de base entre $\mathbb{M}$ et $\mathbb{Q}$

Rappel: Le changement de base entre $\mathbb{M}$ et $\mathbb{Q}$ est fondé sur un ordre partiel $\leq_*$. Dans Sage, cet ordre est appelé ``strongly_fatter``.

$$\mathbb{Q}_P = \sum_{P \leq_* W} \mathbb{M}_W,$$

In [13]:
p = PackedWord([7,6,2,4,3,4,5,1,1])

In [14]:
M(Q[p])

M[762434511] + M[652434411] + M[652323411] + M[542323311]

In [15]:
Q(M[p])

Q[762434511] - Q[652434411] - Q[652323411] + Q[542323311]

In [16]:
matr_chgmt_base_osp(Q,M,3)

[1 0 0 0 0 0 0 0 0 0 0 0 0]
[0 1 0 0 0 0 0 0 0 0 0 0 0]
[0 0 1 0 0 0 0 0 0 0 0 0 0]
[0 0 0 1 0 0 0 0 0 0 0 0 0]
[0 0 0 0 1 0 0 0 0 0 0 0 0]
[0 0 0 0 0 1 0 0 0 0 0 0 0]
[1 0 0 0 0 0 1 0 0 0 0 0 0]
[0 0 1 0 0 0 0 1 0 0 0 0 0]
[0 0 0 1 0 0 0 0 1 0 0 0 0]
[1 0 0 0 0 0 0 0 0 1 0 0 0]
[0 1 0 0 0 0 0 0 0 0 1 0 0]
[0 0 0 0 1 0 0 0 0 0 0 1 0]
[1 0 0 0 0 0 1 0 0 1 0 0 1]

#### Changement de base entre $\mathbb{O}$ et $\mathbb{Q}$

In [17]:
p = PackedWord([7,6,2,4,3,4,5,1,1])

In [18]:
Q(O[p])

Q[761424533] + Q[762434511] + Q[761434522] + Q[761323544] - Q[764124533] - Q[764234511] - Q[764134522] - Q[763123544] - Q[765142433] - Q[765243411] - Q[765143422] - Q[765132344] + Q[765412433] + Q[765423411] + Q[765413422] + Q[765312344]

In [19]:
# O(Q[p]) Comme annoncé, cela prend trop de temps.
%time(O(Q[1,2,2,1])) # Ce simple calcul prend déjà un certain temps. Environ 1.5 sec

CPU times: user 5.7 s, sys: 3.72 ms, total: 5.7 s
Wall time: 5.7 s


O[2121] + O[2211]

In [20]:
matr_chgmt_base_osp(O,Q,3)

[ 1  0  0  0  0  0  0  0  0  0  0  0  0]
[ 0  1 -1  1  0  0  0  0  0  0  0  0  0]
[-1  0  1  0  0  0  0  0  0  0  0  0  0]
[ 0  0 -1  1  0  0  0  0  0  0  0  0  0]
[-1 -1  1 -1  1  0  0  0  0  0  0  0  0]
[ 1  0  0 -1 -1  1  0  0  0  0  0  0  0]
[ 0  0  0  0  0  0  1  1  0  0  0  0  0]
[ 0  0  0  0  0  0 -1  0  0  0  0  0  0]
[ 0  0  0  0  0  0  0 -1  1  0  0  0  0]
[ 0  0  0  0  0  0  0  0  0  1  0  0  0]
[ 0  0  0  0  0  0  0  0  0  0  1  0  0]
[ 0  0  0  0  0  0  0  0  0 -1 -1  1  0]
[ 0  0  0  0  0  0  0  0  0  0  0  0  1]

#### Changement de base entre $\mathbb{P}$ et $\mathbb{R}$

In [21]:
len(R(P[p]))

480

In [22]:
# P(R[p]) Comme annoncé, cela prend trop de temps.
P(R[1,2,1,1]) # Ce simple calcul prend déjà un certain temps. Environ 20 sec

P[1211]

In [23]:
matr_chgmt_base_osp(P,R,3)

[ 1  0  0  0  0  0  0  0  0  0  0  0  0]
[ 0  1 -1  0  1  0  0  0  0  0  0  0  0]
[-1  0  1  0  0  0  0  0  0  0  0  0  0]
[-1 -1  1  1 -1  0  0  0  0  0  0  0  0]
[ 0  0 -1  0  1  0  0  0  0  0  0  0  0]
[ 1  0  0 -1 -1  1  0  0  0  0  0  0  0]
[ 0  0  0  0  0  0  1  0  0  0  0  0  0]
[ 0  0  0  0  0  0  1  1  0  0  0  0  0]
[ 0  0  0  0  0  0  0  0  1 -1  0  0  0]
[ 0  0  0  0  0  0  0  0  0  1  0  0  0]
[ 0  0  0  0  0  0 -1  0  0  0  1  1  0]
[ 0  0  0  0  0  0 -1  0  0  0  0  1  0]
[ 0  0  0  0  0  0  0  0  0  0  0  0  1]

#### Changement de base entre $\mathbb{O}$ et $\mathbb{P}$

In [24]:
p = PackedWord([7,6,2,4,3,4,5,1,1])

In [25]:
O(P[p])

O[773545621]

In [26]:
P(O[p])

P[773545621]

In [27]:
matr_chgmt_base_osp(O,P,3)

[1 0 0 0 0 0 0 0 0 0 0 0 0]
[0 1 0 0 0 0 0 0 0 0 0 0 0]
[0 0 1 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 1 0 0 0 0 0 0 0 0]
[0 0 0 1 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 1 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 1 0 0 0 0 0]
[0 0 0 0 0 0 1 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 1 0]
[0 0 0 0 0 0 0 0 0 1 0 0 0]
[0 0 0 0 0 0 0 0 0 0 1 0 0]
[0 0 0 0 0 0 0 0 1 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 1]

### Produits dans les bases $\mathbb{O}$ et $\mathbb{P}$. 

Je n'ai pas codé les produits et coproduits. Donc pour obtenir le produit de deux éléments dans une de ces bases ou le coproduit d'un élément, je dois changer de base vers une où le produit est codé ($\mathbb{Q}$ ou $\mathbb{R}$). Cependant, comme nous l'avons vu, retourner dans la base initiale est très lent. En conclusion, nous constatons que les temps de calculs deviennent très long à partir de la taille 5.

Le même raisonnement s'applique pour les demis-produits et demis-coproduits.

In [28]:
O[4,3,2,1].coproduct()

O[] # O[4321] + O[1] # O[321] + O[21] # O[21] + O[321] # O[1] + O[4321] # O[]

In [29]:
O[1,2]*O[2,1]

O[4123] + O[4312] + O[2341] + O[4231] + O[3421]

J'ai fait en sorte que ``ascii_art`` affiche la forêt rouge (resp. bleue) pour un élément dans la base $\mathbb{P}$ (resp. $\mathbb{O}$). Grâce à cet affichage, on remarque que le produit correspond au produit de greffes sur les forêts planes et le coproduit à la déconcaténation des arbres. Voici quelques exemples qui en témoignent.

In [30]:
ascii_art(O[1,2])

[ (1, (1, False)) ]
[ |               ]
[ (0, (1, False)) ]

In [31]:
time(ascii_art(O[1,2]**2)) # encore une fois ce calcul prend du temps. Environ 30 sec

CPU times: user 31.8 s, sys: 0 ns, total: 31.8 s
Wall time: 31.8 s


[ (1, (1, False)) ]                                          
[ |               ]                                          
[ (1, (1, False)) ]   [   _______(2, (1, False))         ]   
[ |               ]   [  /               /               ]   
[ (1, (1, False)) ]   [ (1, (1, False)) (0, (1, False))  ]   
[ |               ]   [ |                                ]   
[ (0, (1, False)) ] + [ (0, (1, False))                  ] + 

                                                                             
                                                                             
[   _______(2, (1, False))         ]                                         
[  /               /               ]                                         
[ (0, (1, False)) (1, (1, False))  ]     [ (1, (1, False)), (1, (1, False)) ]
[                 |                ]     [ |                |               ]
[                 (0, (1, False))  ] + 2*[ (0, (1, False))  (0, (1, False)) ]

In [32]:
ascii_art(O[4,3,1,2].coproduct())

       [ (1, (1, False)), (0, (1, False)), (0, (1, False)) ]   
       [ |                                                 ]   
[  ] # [ (0, (1, False))                                   ] + 

[ (1, (1, False)) ]                                          [ (1, (1, False)),
[ |               ]                                          [ |               
[ (0, (1, False)) ] # [ (0, (1, False)), (0, (1, False)) ] + [ (0, (1, False)) 

 (0, (1, False)) ]                         [ (1, (1, False)), (0, (1, False)),
                 ]                         [ |                                
                 ] # [ (0, (1, False)) ] + [ (0, (1, False))                  

 (0, (1, False)) ]       
                 ]       
                 ] # [  ]

J'ai effectué le calcul de deux exemples à la main, on peut voir grâce à l'affichage `ascii` que ces calculs correspondent bien au produit de greffe entre les deux arbres. Contrairement aux calculs précédents, je n'ai pas besoin de repasser dans la base $\mathbb{O}$ (resp. $\mathbb{P}$) donc le calcul est rapide, voire instantané.

In [33]:
a = O[2,2,1,1,1,1,2]
b = O[1,1,2]
ab = O[3,3,4,2,2,1,1,1,1,2] + O[3,3,2,2,1,1,1,1,2,4] + O[3,2,2,1,1,1,1,2,3,4] + O[3,3,2,2,2,2,3,1,1,4] + O[4,4,3,3,3,3,4,1,1,2]

In [34]:
Q(a)*Q(b) - Q(ab)

0

In [35]:
ascii_art(a)

[   _______(1, (1, True))          ]
[  /               /               ]
[ (0, (1, True))  (0, (1, True))   ]
[ |               |                ]
[ (0, (1, True))  (0, (1, False))  ]
[ |                                ]
[ (0, (1, True))                   ]
[ |                                ]
[ (0, (1, False))                  ]

In [36]:
ascii_art(b)

[ (1, (1, False)) ]
[ |               ]
[ (0, (1, True))  ]
[ |               ]
[ (0, (1, False)) ]

In [37]:
ascii_art(ab)

[                       (1, (1, False))             ]   
[                       |                           ]   
[            ___________(1, (1, True))              ]   
[           /                       /               ]   
[   _______(1, (1, True))          (0, (1, False))  ]   
[  /               /                                ]   
[ (0, (1, True))  (0, (1, True))                    ]   
[ |               |                                 ]   
[ (0, (1, True))  (0, (1, False))                   ]   
[ |                                                 ]   
[ (0, (1, True))                                    ]   
[ |                                                 ]   
[ (0, (1, False))                                   ] + 

                                                        
                                                        
[            ___________(2, (1, False))             ]   
[           /                       /               ]   
[   _______(1, (1, True))     

In [38]:
a = P[1,2]
b = P[1,1,2]
ab = P[3,3,4,1,2] + P[3,3,1,2,4] + P[1,2,3,3,4] + P[2,3,1,1,4] + P[3,4,1,1,2]
R(a)*R(b) - R(ab)

0